import { z } from "zod";

export const ActionContentSchema = z.object({
  content: z.string().describe("HTML or text shown inside the badge"),
  position: z.enum(["left", "right"]).optional(),
  rotation: z.number().optional().describe("Degrees of rotation, e.g. -8"),
  icon: z.string().optional().describe("Single emoji to show in the badge"),
});

export const ListItemSchema = z.object({
  clue: z
    .union([z.string(), z.number()])
    .optional()
    .describe("The clue shown next to the blank, e.g. 2024 or '#1' or 'AFC'"),
});

export const MatchupItemSchema = z.object({
  centerText: z
    .string()
    .describe("The center divider text, e.g. 'vs' or '40-22'"),
  context: z
    .union([z.string(), z.number()])
    .optional()
    .describe("Optional label above the matchup, e.g. 'Super Bowl LI'"),
});

export const ListPageSchema = z.object({
  type: z.literal("list"),
  title: z.string(),
  description: z.string().optional(),
  itemsNote: z
    .string()
    .optional()
    .describe(
      "How items will be auto-generated by sync-pages. Examples: '25 items – clues are years descending from 2024', '20 items – clues are rank numbers'.",
    ),
  items: z.array(ListItemSchema).min(1),
  columns: z.number().int().min(1).max(4).optional(),
  actionContent: ActionContentSchema.optional(),
});

export const MatchupPageSchema = z.object({
  type: z.literal("matchup"),
  title: z.string(),
  description: z.string().optional(),
  items: z.array(MatchupItemSchema).min(1),
  columns: z.number().int().min(1).max(4).optional(),
  actionContent: ActionContentSchema.optional(),
});

export type ListPageDraft = z.infer<typeof ListPageSchema>;
export type MatchupPageDraft = z.infer<typeof MatchupPageSchema>;
export type PageDraft = ListPageDraft | MatchupPageDraft;
