import type { PageConfig, PageConfiguration } from './pageTypes.js';

// ─────────────────────────────────────────────────────────────────────────────
// AUTO-GENERATED by excelToJson.ts
// Generated: 2026-08-15T02:58:03.889Z
//
// DO NOT EDIT BY HAND
// ─────────────────────────────────────────────────────────────────────────────

export const booksConfig: Record<string, PageConfig> = {

  'nfl': {
    pages: [
    {
      type: 'toc',
      title: "Table of Contents",
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/1"
    },

    {
      type: 'text',
      title: "How to Play",
      content: "<p class=\"mb-4\">Do You Know Ball? is a collaborative trivia book built for groups &mdash; road trips, tailgates, bars, living rooms. There's no app and no host required. Just open to a page and start playing.</p><h3 class=\"text-lg font-bold text-gray-900 mb-2 print:text-base\">The Basics</h3><ol class=\"list-decimal list-inside space-y-1.5 mb-4\"><li>Open to any page. Every page is its own self-contained trivia challenge.</li><li>Read the prompt out loud to the group (e.g. &ldquo;Name the last 20 MVPs&rdquo;).</li><li>Work together (or split into teams) filling in as many blanks as you can from memory.</li><li>Set a time limit if you want to keep things moving &mdash; 2&ndash;5 minutes works well for most pages.</li><li>Scan the QR code in the footer to reveal the answer key and see how you did.</li></ol><h3 class=\"text-lg font-bold text-gray-900 mt-5 mb-2 print:text-base\">Scoring (Optional)</h3><p class=\"mb-4\">Award 1 point per correct answer. For matchup and bracket pages, award 1 point per correct side. Highest score at the end of the book wins bragging rights &mdash; there's no prize besides pride.</p><h3 class=\"text-lg font-bold text-gray-900 mt-5 mb-2 print:text-base\">Tips</h3><ul class=\"list-disc list-inside space-y-1.5\"><li>Play solo to test yourself, or in a group to see who really knows ball.</li><li>No phones until the QR scan &mdash; looking it up early is cheating.</li><li>Categories and difficulty are noted at the top of every page, so you can start easy and work up to Hard.</li></ul>",
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/2"
    },

    {
      type: 'list',
      title: "NFL All-Time Touchdown Leaders",
      description: "List the top 20 all-time NFL touchdown leaders.",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 20}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/3",
      actionContent: {
        content: "Only one active player is on this list!",
        position: 'left',
        rotation: 2,
        icon: '🏃‍♂️'
      }
    },

    {
      type: 'list',
      title: "Top 20 NFL Career Rushing Leaders",
      description: "List the top 20 all-time NFL career rushing leaders.",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 20}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/4",
      actionContent: {
        content: "There is one active player in this list",
        position: 'right',
        rotation: -1,
        icon: '🏃‍♂️'
      }
    },

    {
      type: 'list',
      title: "Top 20 NFL Career Receiving Yards Leaders",
      description: "List the top 20 all-time NFL career receiving yards leaders.",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 20}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/5",
      actionContent: {
        content: "Only one active player",
        position: 'right',
        rotation: 2,
        icon: '🏈'
      }
    },

    {
      type: 'list',
      title: "NFC East — Top 10 Career Passing Yards (By Player)",
      description: "List the top 10 career passing yard leaders for NFC East teams (yards accumulated while on NFC East teams).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/6",
    },

    {
      type: 'list',
      title: "NFC East — Top 10 Career Rushing Yards (By Player)",
      description: "List the top 10 career rushing yard leaders for NFC East teams (yards accumulated while on NFC East teams).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/7",
    },

    {
      type: 'list',
      title: "NFC East — Top 10 Career Receiving Yards (By Player)",
      description: "List the top 10 career receiving yard leaders for NFC East teams (yards accumulated while on NFC East teams).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/8",
    },

    {
      type: 'list',
      title: "NFC North — Top 10 Career Passing Yards (By Player)",
      description: "List the top 10 career passing yard leaders for NFC North teams (yards accumulated while on NFC North teams).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/9",
    },

    {
      type: 'list',
      title: "NFC North — Top 10 Career Rushing Yards (By Player)",
      description: "List the top 10 career rushing yard leaders for NFC North teams (yards accumulated while on NFC North teams).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/10",
    },

    {
      type: 'list',
      title: "NFC North — Top 10 Career Receiving Yards (By Player)",
      description: "List the top 10 career receiving yard leaders for NFC North teams (yards accumulated while on NFC North teams).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/11",
    },

    {
      type: 'list',
      title: "NFC South — Top 10 Career Passing Yards (By Player)",
      description: "List the top 10 career passing yard leaders for NFC South teams (yards accumulated while on NFC South teams).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/12",
    },

    {
      type: 'list',
      title: "NFC South — Top 10 Career Rushing Yards (By Player)",
      description: "List the top 10 career rushing yard leaders for NFC South teams (yards accumulated while on NFC South teams).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/13",
    },

    {
      type: 'list',
      title: "NFC South — Top 10 Career Receiving Yards (By Player)",
      description: "List the top 10 career receiving yard leaders for NFC South teams (yards accumulated while on NFC South teams).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/14",
    },

    {
      type: 'list',
      title: "NFC West — Top 10 Career Passing Yards (By Player)",
      description: "List the top 10 career passing yard leaders for NFC West teams (yards accumulated while on NFC West teams).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/15",
    },

    {
      type: 'list',
      title: "NFC West — Top 10 Career Rushing Yards (By Player)",
      description: "List the top 10 career rushing yard leaders for NFC West teams (yards accumulated while on NFC West teams).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/16",
    },

    {
      type: 'list',
      title: "NFC West — Top 10 Career Receiving Yards (By Player)",
      description: "List the top 10 career receiving yard leaders for NFC West teams (yards accumulated while on NFC West teams).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/17",
    },

    {
      type: 'list',
      title: "AFC East — Top 10 Career Passing Yards (By Player)",
      description: "List the top 10 career passing yard leaders for AFC East teams (yards accumulated while on AFC East teams).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/18",
    },

    {
      type: 'list',
      title: "AFC East — Top 10 Career Rushing Yards (By Player)",
      description: "List the top 10 career rushing yard leaders for AFC East teams (yards accumulated while on AFC East teams).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/19",
    },

    {
      type: 'list',
      title: "AFC East — Top 10 Career Receiving Yards (By Player)",
      description: "List the top 10 career receiving yard leaders for AFC East teams (yards accumulated while on AFC East teams).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/20",
    },

    {
      type: 'list',
      title: "AFC North — Top 10 Career Passing Yards (By Player)",
      description: "List the top 10 career passing yard leaders for AFC North teams (yards accumulated while on AFC North teams).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/21",
    },

    {
      type: 'list',
      title: "AFC North — Top 10 Career Rushing Yards (By Player)",
      description: "List the top 10 career rushing yard leaders for AFC North teams (yards accumulated while on AFC North teams).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/22",
    },

    {
      type: 'list',
      title: "AFC North — Top 10 Career Receiving Yards (By Player)",
      description: "List the top 10 career receiving yard leaders for AFC North teams (yards accumulated while on AFC North teams).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/23",
    },

    {
      type: 'list',
      title: "AFC South — Top 10 Career Passing Yards (By Player)",
      description: "List the top 10 career passing yard leaders for AFC South teams (yards accumulated while on AFC South teams).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/24",
    },

    {
      type: 'list',
      title: "AFC South — Top 10 Career Rushing Yards (By Player)",
      description: "List the top 10 career rushing yard leaders for AFC South teams (yards accumulated while on AFC South teams).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/25",
    },

    {
      type: 'list',
      title: "AFC South — Top 10 Career Receiving Yards (By Player)",
      description: "List the top 10 career receiving yard leaders for AFC South teams (yards accumulated while on AFC South teams).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/26",
    },

    {
      type: 'list',
      title: "AFC West — Top 10 Career Passing Yards (By Player)",
      description: "List the top 10 career passing yard leaders for AFC West teams (yards accumulated while on AFC West teams).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/27",
    },

    {
      type: 'list',
      title: "AFC West — Top 10 Career Rushing Yards (By Player)",
      description: "List the top 10 career rushing yard leaders for AFC West teams (yards accumulated while on AFC West teams).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/28",
    },

    {
      type: 'list',
      title: "AFC West — Top 10 Career Receiving Yards (By Player)",
      description: "List the top 10 career receiving yard leaders for AFC West teams (yards accumulated while on AFC West teams).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/29",
    },

    {
      type: 'list',
      title: "Top 10 Career Sacks (All-Time)",
      description: "List the top 10 NFL players by career sacks (all-time).",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/30",
    },

    {
      type: 'list',
      title: "Top 10 Career Interceptions (All-Time)",
      description: "List the top 10 NFL players by career interceptions (all-time).",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/31",
    },

    {
      type: 'list',
      title: "Top 10 Career Forced Fumbles (All-Time)",
      description: "List the top 10 NFL players by career forced fumbles (all-time).",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/32",
    },

    {
      type: 'list',
      title: "Top 10 Career Tackles (All-Time)",
      description: "List the top 10 NFL players by career tackles (all-time).",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/33",
    },

    {
      type: 'list',
      title: "Top 10 Career Passing TDs (All-Time)",
      description: "List the top 10 NFL players by career passing touchdowns (all-time).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/34",
    },

    {
      type: 'list',
      title: "Top 10 Career Rushing TDs (All-Time)",
      description: "List the top 10 NFL players by career rushing touchdowns (all-time).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/35",
    },

    {
      type: 'list',
      title: "Top 10 Career Receiving TDs (All-Time)",
      description: "List the top 10 NFL players by career receiving touchdowns (all-time).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/36",
    },

    {
      type: 'list',
      title: "Top 10 Career Scrimmage Yards (All-Time)",
      description: "List the top 10 NFL players by career scrimmage yards (all-time).",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/37",
    },

    {
      type: 'list',
      title: "Top 10 Career Receptions (All-Time)",
      description: "List the top 10 NFL players by career receptions (all-time).",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/38",
    },

    {
      type: 'list',
      title: "Top 10 Career QB Rushing Yards (All-Time)",
      description: "List the top 10 quarterbacks by career rushing yards in NFL history.",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/39",
    },

    {
      type: 'list',
      title: "Top 10 Non-QB Passing Yards (WR/TE/RB) since 2000",
      description: "List the top 10 players in passing yards among wide receivers, tight ends, and running backs (non-QBs) since 2000.",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/40",
    },

    {
      type: 'list',
      title: "Top 10 Players with Most 200+ Rushing Yard Games",
      description: "List the top 10 players with the most games of 200+ rushing yards (all time).",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/41",
    },

    {
      type: 'list',
      title: "Top 10 Players with Most 200+ Receiving Yard Games",
      description: "List the top 10 players with the most games of 200+ receiving yards (all time).",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/42",
    },

    {
      type: 'list',
      title: "Top 10 QBs with Most 400+ Passing Yard Games",
      description: "List the top 10 quarterbacks with the most games of 400+ passing yards (all time).",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/43",
    },

    {
      type: 'list',
      title: "Top 10 Players with Most 3+ Rushing TD Games",
      description: "List the top 10 players with the most games with 3+ rushing touchdowns (all time).",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/44",
    },

    {
      type: 'list',
      title: "Top 10 Players with Most 3+ Receiving TD Games",
      description: "List the top 10 players with the most games with 3+ receiving touchdowns (all time).",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/45",
    },

    {
      type: 'list',
      title: "Top 10 QBs with Most 5+ Passing TD Games",
      description: "List the top 10 quarterbacks with the most games with 5+ passing touchdowns (all time).",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/46",
    },

    {
      type: 'list',
      title: "Top 10 player with the most receiving touchdowns thrown by Aaron Rodgers",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Aaron Rodgers",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/47",
    },

    {
      type: 'list',
      title: "Top 10 player with the most receiving touchdowns thrown by Tom Brady",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Tom Brady",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/48",
    },

    {
      type: 'list',
      title: "Top 10 player with the most receiving touchdowns thrown by Drew Brees",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Drew Brees",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/49",
    },

    {
      type: 'list',
      title: "Top 10 player with the most receiving touchdowns thrown by Peyton Manning",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Peyton Manning",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/50",
    },

    {
      type: 'list',
      title: "Top 10 player with the most receiving touchdowns thrown by Brett Favre",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Brett Favre",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/51",
    },

    {
      type: 'list',
      title: "Top 10 player with the most receiving touchdowns thrown by Philip Rivers",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Philip Rivers",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/52",
    },

    {
      type: 'list',
      title: "Top 10 player with the most receiving touchdowns thrown by Matthew Stafford",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Matthew Stafford",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/53",
    },

    {
      type: 'list',
      title: "Top 10 player with the most receiving touchdowns thrown by Dan Marino",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Dan Marino",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/54",
    },

    {
      type: 'list',
      title: "Top 10 player with the most receiving touchdowns thrown by Ben Roethlisberger",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Ben Roethlisberger",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/55",
    },

    {
      type: 'list',
      title: "Top 10 player with the most receiving touchdowns thrown by Matt Ryan",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Matt Ryan",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/56",
    },

    {
      type: 'list',
      title: "Top 10 player with the most receiving touchdowns thrown by Eli Manning",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Eli Manning",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/57",
    },

    {
      type: 'list',
      title: "Top 10 player with the most receiving touchdowns thrown by Russell Wilson",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Russell Wilson",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/58",
    },

    {
      type: 'list',
      title: "Top 10 player with the most receiving touchdowns thrown by Fran Tarkenton",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Fran Tarkenton",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/59",
    },

    {
      type: 'list',
      title: "Top 10 player with the most receiving touchdowns thrown by John Elway",
      description: "List the top 10 wide receivers with the most receiving touchdowns from John Elway",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/60",
    },

    {
      type: 'list',
      title: "Top 10 player with the most receiving touchdowns thrown by Kirk Cousins",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Kirk Cousins",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/61",
    },

    {
      type: 'list',
      title: "Top 10 player with the most receiving touchdowns thrown by Carson Palmer",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Carson Palmer",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/62",
    },

    {
      type: 'list',
      title: "Top 10 player with the most receiving touchdowns thrown by Warren Moon",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Warren Moon",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/63",
    },

    {
      type: 'list',
      title: "Top 10 player with the most receiving touchdowns thrown by Johnny Unitas",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Johnny Unitas",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/64",
    },

    {
      type: 'list',
      title: "Top 10 player with the most receiving touchdowns thrown by Vinny Testaverde",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Vinny Testaverde",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/65",
    },

    {
      type: 'list',
      title: "Top 10 player with the most receiving touchdowns thrown by Joe Montana",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Joe Montana",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/66",
    },

    {
      type: 'list',
      title: "Top 10 player with the most receiving touchdowns thrown by Joe Flacco",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Joe Flacco",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/67",
    },

    {
      type: 'list',
      title: "Top 10 player with the most receiving touchdowns thrown by Patrick Mahomes",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Patrick Mahomes",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/68",
    },

    {
      type: 'list',
      title: "Top 10 player with the most receiving touchdowns thrown by Dave Krieg",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Dave Krieg",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/69",
    },

    {
      type: 'list',
      title: "Top 10 player with the most receiving touchdowns thrown by Derek Carr",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Derek Carr",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/70",
    },

    {
      type: 'list',
      title: "Top 10 player with the most receiving touchdowns thrown by Jared Goff",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Jared Goff",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/71",
    },

    {
      type: 'list',
      title: "Top 10 player with the most receiving touchdowns thrown by Sonny Jurgensen",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Sonny Jurgensen",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/72",
    },

    {
      type: 'list',
      title: "Super Bowl Era — Top 10 Teams by Most Wins",
      description: "List the top 10 NFL teams with the most regular-season wins since the start of the Super Bowl era (since 1966).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/73",
    },

    {
      type: 'list',
      title: "Super Bowl Era — Top 10 Teams by Most Losses",
      description: "List the top 10 NFL teams with the most regular-season losses since the start of the Super Bowl era (since 1966).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/74",
    },

    {
      type: 'list',
      title: "Super Bowl Era — Top 10 Teams by Most Super Bowl Wins",
      description: "List the top 10 NFL teams with the most Super Bowl wins.",
      category: "All-Time",
      difficulty: 'Easy',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/75",
    },

    {
      type: 'list',
      title: "Super Bowl Era — Top 10 Teams by Most Super Bowl Losses",
      description: "List the top 10 NFL teams with the most Super Bowl losses.",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/76",
    },

    {
      type: 'list',
      title: "Teams with No Super Bowl Wins",
      description: "List the NFL teams that have never won a Super Bowl.",
      category: "All-Time",
      difficulty: 'Easy',
      items: [
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
      ],
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/77",
    },

    {
      type: 'list',
      title: "Super Bowl Era — Top 10 Teams by Playoff Wins",
      description: "List the top 10 NFL teams with the most playoff wins since the start of the Super Bowl era (since 1966).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/78",
    },

    {
      type: 'list',
      title: "Super Bowl Era — Top 10 QBs by Playoff Passing TDs",
      description: "List the top 10 quarterbacks with the most passing touchdowns in the playoffs since the start of the Super Bowl era (since 1966).",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/79",
    },

    {
      type: 'list',
      title: "Super Bowl Era — Top 10 QBs by Playoff Passing Yards",
      description: "List the top 10 quarterbacks with the most passing yards in the playoffs since the start of the Super Bowl era (since 1966).",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/80",
    },

    {
      type: 'list',
      title: "Super Bowl Era — Top 10 Players by Playoff Rushing Yards",
      description: "List the top 10 players with the most rushing yards in the playoffs since the start of the Super Bowl era (since 1966).",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/81",
    },

    {
      type: 'list',
      title: "Super Bowl Era — Top 10 Players by Playoff Receiving Yards",
      description: "List the top 10 players with the most receiving yards in the playoffs since the start of the Super Bowl era (since 1966).",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/82",
    },

    {
      type: 'list',
      title: "NFL Career Earnings Leaders",
      description: "List the 10 NFL players with the highest total on-field career earnings (salary and bonuses) all time, using Spotrac’s NFL Career Earnings leaderboard.",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/83",
    },

    {
      type: 'list',
      title: "NFL MVP Challenge",
      description: "List the NFL Most Valuable Players (2000-2024).",
      category: "Awards",
      difficulty: 'Hard',
      items: Array.from({length: 25}, (_, i) => ({
        clue: 2024 - i,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/84",
      actionContent: {
        content: "One Year has Co-MVPs bonus points if you get the year and both players right!",
        position: 'right',
        rotation: 3,
        icon: '🧠'
      }
    },

    {
      type: 'list',
      title: "NFL Defensive Player of the Year",
      description: "List the NFL Defensive Players of the Year (2015-2024).",
      category: "Awards",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: 2024 - i,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/85",
    },

    {
      type: 'list',
      title: "NFL Offensive Rookie of the Year",
      description: "List the NFL Offensive Rookies of the Year (2015-2024).",
      category: "Awards",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: 2024 - i,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/86",
    },

    {
      type: 'list',
      title: "NFL Defensive Rookie of the Year",
      description: "List the NFL Defensive Rookies of the Year (2015-2024).",
      category: "Awards",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: 2024 - i,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/87",
    },

    {
      type: 'list',
      title: "NFL Comeback Player of the Year",
      description: "List the NFL Comeback Players of the Year (2015-2024).",
      category: "Awards",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: 2024 - i,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/88",
    },

    {
      type: 'list',
      title: "Last 10 Super Bowl MVPs",
      description: "Name the Super Bowl MVPs from the last 10 Super Bowls.",
      category: "Awards",
      difficulty: 'Medium',
      items: [
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
      ],
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/89",
    },

    {
      type: 'list',
      title: "NFL Money Kings: Top 5 QBs by AAV (2025)",
      description: "List the 5 highest-paid quarterbacks in the NFL by average annual contract value (AAV) for the 2025 season.",
      category: "Contracts",
      difficulty: 'Medium',
      items: [
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
      ],
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/90",
    },

    {
      type: 'list',
      title: "NFL Money Kings: Top 5 WRs by AAV (2025)",
      description: "List the 5 highest-paid wide receivers in the NFL by average annual contract value (AAV) for the 2025 season.",
      category: "Contracts",
      difficulty: 'Medium',
      items: [
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
      ],
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/91",
    },

    {
      type: 'list',
      title: "NFL Money Kings: Top 5 RBs by AAV (2025)",
      description: "List the 5 highest-paid running backs in the NFL by average annual contract value (AAV) for the 2025 season.",
      category: "Contracts",
      difficulty: 'Medium',
      items: [
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
      ],
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/92",
    },

    {
      type: 'list',
      title: "Most Recent Season Fantasy Football Top 10 QBs (PPR)",
      description: "List the top 10 fantasy scoring quarterbacks in full PPR during the most recently completed NFL season.",
      category: "Fantasy",
      difficulty: 'Easy',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/93",
    },

    {
      type: 'list',
      title: "Most Recent Season Fantasy Football Top 10 RBs (PPR)",
      description: "List the top 10 fantasy scoring running backs in full PPR during the most recently completed NFL season.",
      category: "Fantasy",
      difficulty: 'Easy',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/94",
    },

    {
      type: 'list',
      title: "Most Recent Season Fantasy Football Top 10 WRs (PPR)",
      description: "List the top 10 fantasy scoring wide receivers in full PPR during the most recently completed NFL season.",
      category: "Fantasy",
      difficulty: 'Easy',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/95",
    },

    {
      type: 'list',
      title: "Most Recent Season Fantasy Football Top 10 TEs (PPR)",
      description: "List the top 10 fantasy scoring tight ends in full PPR during the most recently completed NFL season.",
      category: "Fantasy",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/96",
    },

    {
      type: 'list',
      title: "Most Recent Season Fantasy Football Top 10 Rookie Scorers (PPR)",
      description: "List the top 10 rookie fantasy scorers in full PPR during the most recently completed NFL season.",
      category: "Fantasy",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/97",
    },

    {
      type: 'list',
      title: "All-Time Fantasy Football Top 10 Seasons (PPR)",
      description: "List the top 10 single-season fantasy scoring seasons in full PPR in NFL history (overall).",
      category: "Fantasy",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/98",
    },

    {
      type: 'list',
      title: "All-Time Fantasy Football Top 10 QB Seasons (PPR)",
      description: "List the top 10 single-season fantasy scoring seasons in full PPR by quarterbacks in NFL history.",
      category: "Fantasy",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/99",
    },

    {
      type: 'list',
      title: "All-Time Fantasy Football Top 10 RB Seasons (PPR)",
      description: "List the top 10 single-season fantasy scoring seasons in full PPR by running backs in NFL history.",
      category: "Fantasy",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/100",
    },

    {
      type: 'list',
      title: "All-Time Fantasy Football Top 10 WR Seasons (PPR)",
      description: "List the top 10 single-season fantasy scoring seasons in full PPR by wide receivers in NFL history.",
      category: "Fantasy",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/101",
    },

    {
      type: 'list',
      title: "All-Time Fantasy Football Top 10 TE Seasons (PPR)",
      description: "List the top 10 single-season fantasy scoring seasons in full PPR by tight ends in NFL history.",
      category: "Fantasy",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/102",
    },

    {
      type: 'list',
      title: "All-Time Fantasy Football Top 10 Rookie Seasons (PPR)",
      description: "List the top 10 rookie single-season fantasy scoring seasons in full PPR in NFL history.",
      category: "Fantasy",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/103",
    },

    {
      type: 'list',
      title: "Most Recent Season — Top 10 Most Fantasy Points in a Single Game (PPR)",
      description: "List the top 10 single-game fantasy point totals in full PPR from the most recently completed NFL season.",
      category: "Fantasy",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/104",
    },

    {
      type: 'list',
      title: "Super Bowl Era — Top 10 Most Fantasy Points in a Single Game (PPR)",
      description: "List the top 10 single-game fantasy point totals in full PPR since the start of the Super Bowl era.",
      category: "Fantasy",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/105",
    },

    {
      type: 'list',
      title: "2024 Fantasy Football Top 10 (PPR)",
      description: "List the top 10 overall fantasy scorers in full PPR during the 2024 regular season.",
      category: "Other",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/106",
      actionContent: {
        content: "Half are non-QB",
        position: 'right',
        rotation: 3,
        icon: '🏈'
      }
    },

    {
      type: 'bracket',
      title: "Guess the Season — Playoff Bracket",
      description: "Fill in the teams and guess the year.",
      category: "Playoffs",
      subcategory: "Bracket",
      difficulty: 'Hard',
      clueStyle: "1990-2019: Patriots, Steelers, Ravens, Colts, Jets, Chiefs / Falcons, Bears, Eagles, Seahawks, Saints, Packers",
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/107",
      actionContent: {
        content: "How many teams can you place correctly?",
        position: 'right',
        rotation: -8,
        icon: '🏆'
      }
    },

    {
      type: 'bracket',
      title: "Guess the Season — Playoff Bracket",
      description: "Fill in the teams and guess the year.",
      category: "Playoffs",
      subcategory: "Bracket",
      difficulty: 'Hard',
      clueStyle: "2020+: Chiefs, Bills, Ravens, Texans, Chargers, Steelers, Broncos / Lions, Eagles, Buccaneers, Rams, Vikings, Commanders, Packers",
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/108",
      actionContent: {
        content: "How many teams can you place correctly?",
        position: 'right',
        rotation: -8,
        icon: '🏆'
      }
    },

    {
      type: 'bracket',
      title: "Guess the Season — Playoff Bracket",
      description: "Fill in the teams and guess the year.",
      category: "Playoffs",
      subcategory: "Bracket",
      difficulty: 'Hard',
      clueStyle: "1990-2019: Broncos, Patriots, Texans, Ravens, Colts, Bengals / Falcons, 49ers, Packers, Redskins, Seahawks, Vikings",
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/109",
      actionContent: {
        content: "How many teams can you place correctly?",
        position: 'right',
        rotation: -8,
        icon: '🏆'
      }
    },

    {
      type: 'bracket',
      title: "Guess the Season — Playoff Bracket",
      description: "Fill in the teams and guess the year.",
      category: "Playoffs",
      subcategory: "Bracket",
      difficulty: 'Hard',
      clueStyle: "1990-2019: Patriots, Colts, Chargers, Steelers, Jaguars, Titans / Cowboys, Packers, Seahawks, Buccaneers, Giants, Redskins",
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/110",
      actionContent: {
        content: "How many teams can you place correctly?",
        position: 'right',
        rotation: -8,
        icon: '🏆'
      }
    },

    {
      type: 'bracket',
      title: "Guess the Season — Playoff Bracket",
      description: "Fill in the teams and guess the year.",
      category: "Playoffs",
      subcategory: "Bracket",
      difficulty: 'Hard',
      clueStyle: "1990-2019: Colts, Broncos, Bengals, Patriots, Jaguars, Steelers / Seahawks, Bears, Buccaneers, Giants, Panthers, Redskins",
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/111",
      actionContent: {
        content: "How many teams can you place correctly?",
        position: 'right',
        rotation: -8,
        icon: '🏆'
      }
    },

    {
      type: 'bracket',
      title: "Guess the Season — Playoff Bracket",
      description: "Fill in the teams and guess the year.",
      category: "Playoffs",
      subcategory: "Bracket",
      difficulty: 'Hard',
      clueStyle: "1990-2019: Titans, Raiders, Dolphins, Ravens, Broncos, Colts / Giants, Vikings, Saints, Eagles, Buccaneers, Rams",
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/112",
      actionContent: {
        content: "How many teams can you place correctly?",
        position: 'right',
        rotation: -8,
        icon: '🏆'
      }
    },

    {
      type: 'bracket',
      title: "Guess the Season — Playoff Bracket",
      description: "Fill in the teams and guess the year.",
      category: "Playoffs",
      subcategory: "Bracket",
      difficulty: 'Hard',
      clueStyle: "1990-2019: Bills, Broncos, Oilers, Chiefs, Raiders, Jets / Redskins, Lions, Saints, Bears, Cowboys, Falcons",
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/113",
      actionContent: {
        content: "How many teams can you place correctly?",
        position: 'right',
        rotation: -8,
        icon: '🏆'
      }
    },

    {
      type: 'bracket',
      title: "Guess the Season — Playoff Bracket",
      description: "Fill in the teams and guess the year.",
      category: "Playoffs",
      subcategory: "Bracket",
      difficulty: 'Hard',
      clueStyle: "1990-2019: Broncos, Jets, Jaguars, Dolphins, Bills, Patriots / Vikings, Falcons, Cowboys, 49ers, Packers, Cardinals",
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/114",
      actionContent: {
        content: "How many teams can you place correctly?",
        position: 'right',
        rotation: -8,
        icon: '🏆'
      }
    },

    {
      type: 'bracket',
      title: "Guess the Season — Playoff Bracket",
      description: "Fill in the teams and guess the year.",
      category: "Playoffs",
      subcategory: "Bracket",
      difficulty: 'Hard',
      clueStyle: "1990-2019: Raiders, Titans, Steelers, Jets, Colts, Browns / Eagles, Buccaneers, Packers, 49ers, Giants, Falcons",
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/115",
      actionContent: {
        content: "How many teams can you place correctly?",
        position: 'right',
        rotation: -8,
        icon: '🏆'
      }
    },

    {
      type: 'bracket',
      title: "Guess the Season — Playoff Bracket",
      description: "Fill in the teams and guess the year.",
      category: "Playoffs",
      subcategory: "Bracket",
      difficulty: 'Hard',
      clueStyle: "1990-2019: Colts, Chargers, Patriots, Bengals, Jets, Ravens / Saints, Vikings, Cowboys, Cardinals, Packers, Eagles",
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/116",
      actionContent: {
        content: "How many teams can you place correctly?",
        position: 'right',
        rotation: -8,
        icon: '🏆'
      }
    },

    {
      type: 'bracket',
      title: "Guess the Season — Playoff Bracket",
      description: "Fill in the teams and guess the year.",
      category: "Playoffs",
      subcategory: "Bracket",
      difficulty: 'Medium',
      clueStyle: "2020+: Titans, Chiefs, Bills, Bengals, Raiders, Patriots, Steelers / Packers, Buccaneers, Cowboys, Rams, Cardinals, 49ers, Eagles",
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/117",
    },

    {
      type: 'bracket',
      title: "Guess the Season — Playoff Bracket",
      description: "Fill in the teams and guess the year.",
      category: "Playoffs",
      subcategory: "Bracket",
      difficulty: 'Medium',
      clueStyle: "2020+: Broncos, Patriots, Jaguars, Steelers, Texans, Bills, Chargers / Seahawks, Bears, Eagles, Panthers, Rams, 49ers, Packers",
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/118",
    },

    {
      type: 'bracket',
      title: "Guess the Season — Playoff Bracket",
      description: "Fill in the teams and guess the year.",
      category: "Playoffs",
      subcategory: "Bracket",
      difficulty: 'Medium',
      clueStyle: "1990-2019: Chiefs, Patriots, Texans, Ravens, Chargers, Colts / Saints, Rams, Bears, Cowboys, Seahawks, Eagles",
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/119",
    },

    {
      type: 'matchup',
      title: "Last 10 AFC Championship Games",
      description: "Fill in the teams that played in each AFC Championship game.",
      category: "Playoffs",
      subcategory: "Matchups",
      difficulty: 'Medium',
      items: [
        { centerText: "vs", context: "2024" },
        { centerText: "vs", context: "2023" },
        { centerText: "vs", context: "2022" },
        { centerText: "vs", context: "2021" },
        { centerText: "vs", context: "2020" },
        { centerText: "vs", context: "2019" },
        { centerText: "vs", context: "2018" },
        { centerText: "vs", context: "2017" },
        { centerText: "vs", context: "2016" },
        { centerText: "vs", context: "2015" },
      ],
      columns: 2,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/120",
    },

    {
      type: 'matchup',
      title: "Last 10 NFC Championship Games",
      description: "Fill in the teams that played in each NFC Championship game.",
      category: "Playoffs",
      subcategory: "Matchups",
      difficulty: 'Medium',
      items: [
        { centerText: "vs", context: "2024" },
        { centerText: "vs", context: "2023" },
        { centerText: "vs", context: "2022" },
        { centerText: "vs", context: "2021" },
        { centerText: "vs", context: "2020" },
        { centerText: "vs", context: "2019" },
        { centerText: "vs", context: "2018" },
        { centerText: "vs", context: "2017" },
        { centerText: "vs", context: "2016" },
        { centerText: "vs", context: "2015" },
      ],
      columns: 2,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/121",
    },

    {
      type: 'matchup',
      title: "Super Bowl Matchups by Score",
      description: "Name the teams that played in these Super Bowls based on the final score.",
      category: "Playoffs",
      subcategory: "Matchups",
      difficulty: 'Hard',
      items: [
        { centerText: "31-17", context: "Super Bowl LVIII (2024)" },
        { centerText: "38-35", context: "Super Bowl LVII (2023)" },
        { centerText: "23-20", context: "Super Bowl LVI (2022)" },
        { centerText: "31-9", context: "Super Bowl LV (2021)" },
        { centerText: "31-20", context: "Super Bowl LIV (2020)" },
        { centerText: "13-3", context: "Super Bowl LIII (2019)" },
      ],
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/122",
      actionContent: {
        content: "Some of these were nail-biters, others were blowouts!",
        position: 'right',
        rotation: -2,
        icon: '🏆'
      }
    },

    {
      type: 'list',
      title: "NFC East — Top 10 Passing Yards (Last 10 Seasons)",
      description: "List the top 10 passing yard leaders from the most recent 10 NFL seasons among NFC East teams.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/123",
    },

    {
      type: 'list',
      title: "NFC East — Top 10 Rushing Yards (Last 10 Seasons)",
      description: "List the top 10 rushing yard leaders from the most recent 10 NFL seasons among NFC East teams.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/124",
    },

    {
      type: 'list',
      title: "NFC East — Top 10 Receiving Yards (Last 10 Seasons)",
      description: "List the top 10 receiving yard leaders from the most recent 10 NFL seasons among NFC East teams.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/125",
    },

    {
      type: 'list',
      title: "NFC North — Top 10 Passing Yards (Last 10 Seasons)",
      description: "List the top 10 passing yard leaders from the most recent 10 NFL seasons among NFC North teams.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/126",
    },

    {
      type: 'list',
      title: "NFC North — Top 10 Rushing Yards (Last 10 Seasons)",
      description: "List the top 10 rushing yard leaders from the most recent 10 NFL seasons among NFC North teams.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/127",
    },

    {
      type: 'list',
      title: "NFC North — Top 10 Receiving Yards (Last 10 Seasons)",
      description: "List the top 10 receiving yard leaders from the most recent 10 NFL seasons among NFC North teams.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/128",
    },

    {
      type: 'list',
      title: "NFC South — Top 10 Passing Yards (Last 10 Seasons)",
      description: "List the top 10 passing yard leaders from the most recent 10 NFL seasons among NFC South teams.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/129",
    },

    {
      type: 'list',
      title: "NFC South — Top 10 Rushing Yards (Last 10 Seasons)",
      description: "List the top 10 rushing yard leaders from the most recent 10 NFL seasons among NFC South teams.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/130",
    },

    {
      type: 'list',
      title: "NFC South — Top 10 Receiving Yards (Last 10 Seasons)",
      description: "List the top 10 receiving yard leaders from the most recent 10 NFL seasons among NFC South teams.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/131",
    },

    {
      type: 'list',
      title: "NFC West — Top 10 Passing Yards (Last 10 Seasons)",
      description: "List the top 10 passing yard leaders from the most recent 10 NFL seasons among NFC West teams.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/132",
    },

    {
      type: 'list',
      title: "NFC West — Top 10 Rushing Yards (Last 10 Seasons)",
      description: "List the top 10 rushing yard leaders from the most recent 10 NFL seasons among NFC West teams.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/133",
    },

    {
      type: 'list',
      title: "NFC West — Top 10 Receiving Yards (Last 10 Seasons)",
      description: "List the top 10 receiving yard leaders from the most recent 10 NFL seasons among NFC West teams.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/134",
    },

    {
      type: 'list',
      title: "AFC East — Top 10 Passing Yards (Last 10 Seasons)",
      description: "List the top 10 passing yard leaders from the most recent 10 NFL seasons among AFC East teams.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/135",
    },

    {
      type: 'list',
      title: "AFC East — Top 10 Rushing Yards (Last 10 Seasons)",
      description: "List the top 10 rushing yard leaders from the most recent 10 NFL seasons among AFC East teams.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/136",
    },

    {
      type: 'list',
      title: "AFC East — Top 10 Receiving Yards (Last 10 Seasons)",
      description: "List the top 10 receiving yard leaders from the most recent 10 NFL seasons among AFC East teams.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/137",
    },

    {
      type: 'list',
      title: "AFC North — Top 10 Passing Yards (Last 10 Seasons)",
      description: "List the top 10 passing yard leaders from the most recent 10 NFL seasons among AFC North teams.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/138",
    },

    {
      type: 'list',
      title: "AFC North — Top 10 Rushing Yards (Last 10 Seasons)",
      description: "List the top 10 rushing yard leaders from the most recent 10 NFL seasons among AFC North teams.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/139",
    },

    {
      type: 'list',
      title: "AFC North — Top 10 Receiving Yards (Last 10 Seasons)",
      description: "List the top 10 receiving yard leaders from the most recent 10 NFL seasons among AFC North teams.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/140",
    },

    {
      type: 'list',
      title: "AFC South — Top 10 Passing Yards (Last 10 Seasons)",
      description: "List the top 10 passing yard leaders from the most recent 10 NFL seasons among AFC South teams.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/141",
    },

    {
      type: 'list',
      title: "AFC South — Top 10 Rushing Yards (Last 10 Seasons)",
      description: "List the top 10 rushing yard leaders from the most recent 10 NFL seasons among AFC South teams.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/142",
    },

    {
      type: 'list',
      title: "AFC South — Top 10 Receiving Yards (Last 10 Seasons)",
      description: "List the top 10 receiving yard leaders from the most recent 10 NFL seasons among AFC South teams.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/143",
    },

    {
      type: 'list',
      title: "AFC West — Top 10 Passing Yards (Last 10 Seasons)",
      description: "List the top 10 passing yard leaders from the most recent 10 NFL seasons among AFC West teams.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/144",
    },

    {
      type: 'list',
      title: "AFC West — Top 10 Rushing Yards (Last 10 Seasons)",
      description: "List the top 10 rushing yard leaders from the most recent 10 NFL seasons among AFC West teams.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/145",
    },

    {
      type: 'list',
      title: "AFC West — Top 10 Receiving Yards (Last 10 Seasons)",
      description: "List the top 10 receiving yard leaders from the most recent 10 NFL seasons among AFC West teams.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/146",
    },

    {
      type: 'list',
      title: "Top 10 Sacks (Last 10 Seasons)",
      description: "List the top 10 NFL players by total sacks over the most recent 10 NFL seasons.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/147",
    },

    {
      type: 'list',
      title: "Top 10 Interceptions (Last 10 Seasons)",
      description: "List the top 10 NFL players by total interceptions over the most recent 10 NFL seasons.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/148",
    },

    {
      type: 'list',
      title: "Top 10 Forced Fumbles (Last 10 Seasons)",
      description: "List the top 10 NFL players by total forced fumbles over the most recent 10 NFL seasons.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/149",
    },

    {
      type: 'list',
      title: "Top 10 Tackles (Last 10 Seasons)",
      description: "List the top 10 NFL players by total tackles over the most recent 10 NFL seasons.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/150",
    },

    {
      type: 'list',
      title: "Last 10 Super Bowl Winners",
      description: "Name the winners of the last 10 Super Bowls.",
      category: "Recent",
      difficulty: 'Easy',
      items: [
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
      ],
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/151",
    },

    {
      type: 'list',
      title: "Last 10 Seasons: Most Passing TDs",
      description: "List the top 10 NFL players by total passing touchdowns over the most recent 10 NFL seasons.",
      category: "Recent",
      difficulty: 'Easy',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/152",
    },

    {
      type: 'list',
      title: "Last 10 Seasons: Most Rushing TDs",
      description: "List the top 10 NFL players by total rushing touchdowns over the most recent 10 NFL seasons.",
      category: "Recent",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/153",
    },

    {
      type: 'list',
      title: "Last 10 Seasons: Most Receiving TDs",
      description: "List the top 10 NFL players by total receiving touchdowns over the most recent 10 NFL seasons.",
      category: "Recent",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/154",
    },

    {
      type: 'list',
      title: "Top 10 RB Receiving Yards (Last 10 Seasons)",
      description: "List the top 10 running backs in receiving yards over the most recent 10 NFL seasons.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/155",
    },

    {
      type: 'list',
      title: "Top 10 players with the most receiving touchdowns thrown by Josh Allen",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Josh Allen",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/156",
    },

    {
      type: 'list',
      title: "Top 10 players with the most receiving touchdowns thrown by Lamar Jackson",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Lamar Jackson",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/157",
    },

    {
      type: 'list',
      title: "Top 10 players with the most receiving touchdowns thrown by Joe Burrow",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Joe Burrow",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/158",
    },

    {
      type: 'list',
      title: "Top 10 players with the most receiving touchdowns thrown by Justin Herbert",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Justin Herbert",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/159",
    },

    {
      type: 'list',
      title: "Top 10 players with the most receiving touchdowns thrown by Dak Prescott",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Dak Prescott",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/160",
    },

    {
      type: 'list',
      title: "Top 10 players with the most receiving touchdowns thrown by Jalen Hurts",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Jalen Hurts",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/161",
    },

    {
      type: 'list',
      title: "Top 10 players with the most receiving touchdowns thrown by Trevor Lawrence",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Trevor Lawrence",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/162",
    },

    {
      type: 'list',
      title: "Top 10 players with the most receiving touchdowns thrown by Brock Purdy",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Brock Purdy",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/163",
    },

    {
      type: 'list',
      title: "Top 10 players with the most receiving touchdowns thrown by C.J. Stroud",
      description: "List the top 10 wide receivers with the most receiving touchdowns from C.J. Stroud",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/164",
    },

    {
      type: 'list',
      title: "Top 10 players with the most receiving touchdowns thrown by Jordan Love",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Jordan Love",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/165",
    },

    {
      type: 'list',
      title: "Top 10 players with the most receiving touchdowns thrown by Baker Mayfield",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Baker Mayfield",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/166",
    },

    {
      type: 'list',
      title: "Most Recent Season — Top 10 Teams by Points Scored",
      description: "List the top 10 NFL teams by total points scored in the most recently completed NFL season.",
      category: "Recent",
      difficulty: 'Easy',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/167",
    },

    {
      type: 'list',
      title: "Most Recent Season — Top 10 Teams by Points Allowed",
      description: "List the top 10 NFL teams that gave up the most points (points allowed) in the most recently completed NFL season.",
      category: "Recent",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/168",
    },

    {
      type: 'list',
      title: "Most Recent Postseason — Top 10 Players by Passing Yards",
      description: "List the top 10 players in passing yards during the most recently completed NFL postseason.",
      category: "Recent",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/169",
    },

    {
      type: 'list',
      title: "Most Recent Postseason — Top 10 Players by Rushing Yards",
      description: "List the top 10 players in rushing yards during the most recently completed NFL postseason.",
      category: "Recent",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/170",
    },

    {
      type: 'list',
      title: "Most Recent Postseason — Top 10 Players by Receiving Yards",
      description: "List the top 10 players in receiving yards during the most recently completed NFL postseason.",
      category: "Recent",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/171",
    },

    {
      type: 'list',
      title: "Most Recent Postseason — Top 10 Players by Total TDs",
      description: "List the top 10 players by total touchdowns (rushing + receiving + passing) in the most recently completed NFL postseason.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/172",
    },

    {
      type: 'list',
      title: "Most Recent Postseason — Top 10 Teams by Points Scored",
      description: "List the top 10 teams by total points scored in the most recently completed NFL postseason.",
      category: "Recent",
      difficulty: 'Easy',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/173",
    },

    {
      type: 'list',
      title: "Last 10 Postseasons — Top 10 Teams by Playoff Wins",
      description: "List the top 10 NFL teams by total playoff wins across the most recent 10 postseasons.",
      category: "Recent",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/174",
    },

    {
      type: 'list',
      title: "Last 10 Postseasons — Top 10 QBs by Playoff Wins",
      description: "List the top 10 quarterbacks by playoff wins across the most recent 10 postseasons.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/175",
    },

    {
      type: 'list',
      title: "Players with the most receiving yards last season",
      description: "Name the NFL players with the most receiving yards last season",
      category: "Recent",
      difficulty: 'Medium',
      items: [
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
      ],
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/176",
    },

    {
      type: 'list',
      title: "Players with the most rushing yards last season",
      description: "Name the NFL players with the most rushing yards last season",
      category: "Recent",
      difficulty: 'Medium',
      items: [
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
      ],
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/177",
    },

    {
      type: 'list',
      title: "Players with the most passing yards last season",
      description: "Name the NFL players with the most passing yards last season",
      category: "Recent",
      difficulty: 'Medium',
      items: [
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
      ],
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/178",
    },

    {
      type: 'list',
      title: "Top 10 Scrimmage Yard Leaders (Last 10 Seasons)",
      description: "List the top 10 players in total scrimmage yards over the most recent 10 NFL seasons.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/179",
    },

    {
      type: 'list',
      title: "Teams with the Least Wins (Last 10 Seasons)",
      description: "List the top 10 NFL teams with the fewest total wins over the most recent 10 seasons.",
      category: "Recent",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/180",
    },

    {
      type: 'list',
      title: "Teams with the Most Wins (Last 10 Seasons)",
      description: "List the top 10 NFL teams with the most total wins over the most recent 10 seasons.",
      category: "Recent",
      difficulty: 'Easy',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/181",
    },

    {
      type: 'list',
      title: "Top 20 Single Season NFL Rushing Records",
      description: "List the top 20 single season NFL rushing records.",
      category: "Single-Season",
      difficulty: 'Medium',
      items: Array.from({length: 20}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/182",
      actionContent: {
        content: "2 RBs show up twice and there is a tie at #12",
        position: 'left',
        rotation: -3,
        icon: '🏃‍♂️'
      }
    },

    {
      type: 'list',
      title: "Top 20 Single Season NFL Receiving Yards Records",
      description: "List the top 20 single season NFL receiving yards records.",
      category: "Single-Season",
      difficulty: 'Medium',
      items: Array.from({length: 20}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/183",
    },

    {
      type: 'list',
      title: "Top 10 Single-Season Passing TDs",
      description: "List the top 10 single-season passing touchdown totals in NFL history.",
      category: "Single-Season",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/184",
    },

    {
      type: 'list',
      title: "Top 10 Single-Season Rushing TDs",
      description: "List the top 10 single-season rushing touchdown totals in NFL history.",
      category: "Single-Season",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/185",
    },

    {
      type: 'list',
      title: "Top 10 Single-Season Receiving TDs",
      description: "List the top 10 single-season receiving touchdown totals in NFL history.",
      category: "Single-Season",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/186",
    },

    {
      type: 'list',
      title: "Top 10 Single-Season Scrimmage Yards",
      description: "List the top 10 single-season scrimmage yard totals in NFL history.",
      category: "Single-Season",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/187",
    },

    {
      type: 'list',
      title: "Top 10 Single-Season Receptions",
      description: "List the top 10 single-season reception totals in NFL history.",
      category: "Single-Season",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/188",
    },

    {
      type: 'list',
      title: "Top 10 Single-Season QB Rushing Yards",
      description: "List the top 10 single-season rushing yard totals by quarterbacks in NFL history.",
      category: "Single-Season",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/189",
    },

    {
      type: 'list',
      title: "Top 10 Single-Season Sacks",
      description: "List the top 10 single-season sack totals in NFL history.",
      category: "Single-Season",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/190",
    },

    {
      type: 'list',
      title: "Top 10 Single-Season Interceptions (Player)",
      description: "List the top 10 single-season interception totals by a player in NFL history.",
      category: "Single-Season",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/191",
    },

    {
      type: 'list',
      title: "Top 10 Single-Season Team Sacks",
      description: "List the top 10 single-season team sack totals in NFL history.",
      category: "Single-Season",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/192",
    },

    {
      type: 'list',
      title: "Top 10 Single-Season Team Points Scored",
      description: "List the top 10 single-season team points scored totals in NFL history.",
      category: "Single-Season",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://dykbtrivia.com/answers/nfl/193",
    }
    ],
    getPageConfiguration(pageNum: number) {
      const pageIndex = pageNum - 1;
      if (pageIndex >= 0 && pageIndex < this.pages.length) {
        return this.pages[pageIndex];
      }
      return {
        type: 'text',
        content: `This is page ${pageNum} of our ${'nfl'.toUpperCase()} book. The content for this page is dynamically generated.`,
        answerKeyUrl: `https://example.com/page-${pageNum}-answers`
      };
    },
    getAnswerKeyUrl(pageNum: number): string {
      const pageConfiguration = this.getPageConfiguration(pageNum);
      return pageConfiguration.answerKeyUrl || `https://example.com/page-${pageNum}-answers`;
    },
    pageExists(pageNum: number): boolean {
      return pageNum >= 1 && pageNum <= this.pages.length;
    }
  },

  'nba': {
    pages: [
    {
      type: 'text',
      title: "How to Play",
      content: "<p class=\"mb-4\">Do You Know Ball? is a collaborative trivia book built for groups &mdash; road trips, tailgates, bars, living rooms. There's no app and no host required. Just open to a page and start playing.</p><h3 class=\"text-lg font-bold text-gray-900 mb-2 print:text-base\">The Basics</h3><ol class=\"list-decimal list-inside space-y-1.5 mb-4\"><li>Open to any page. Every page is its own self-contained trivia challenge.</li><li>Read the prompt out loud to the group (e.g. &ldquo;Name the last 20 MVPs&rdquo;).</li><li>Work together (or split into teams) filling in as many blanks as you can from memory.</li><li>Set a time limit if you want to keep things moving &mdash; 2&ndash;5 minutes works well for most pages.</li><li>Scan the QR code in the footer to reveal the answer key and see how you did.</li></ol><h3 class=\"text-lg font-bold text-gray-900 mt-5 mb-2 print:text-base\">Scoring (Optional)</h3><p class=\"mb-4\">Award 1 point per correct answer. For matchup and bracket pages, award 1 point per correct side. Highest score at the end of the book wins bragging rights &mdash; there's no prize besides pride.</p><h3 class=\"text-lg font-bold text-gray-900 mt-5 mb-2 print:text-base\">Tips</h3><ul class=\"list-disc list-inside space-y-1.5\"><li>Play solo to test yourself, or in a group to see who really knows ball.</li><li>No phones until the QR scan &mdash; looking it up early is cheating.</li><li>Categories and difficulty are noted at the top of every page, so you can start easy and work up to Hard.</li></ul>",
      answerKeyUrl: "https://dykbtrivia.com/answers/nba/1"
    },

    {
      type: 'teams',
      title: "NBA — Franchise Leaders: All-Time Scoring (30 Teams)",
      description: "Name each NBA team’s all-time leading scorer",
      answerKeyUrl: "https://dykbtrivia.com/answers/nba/2",
    }
    ],
    getPageConfiguration(pageNum: number) {
      const pageIndex = pageNum - 1;
      if (pageIndex >= 0 && pageIndex < this.pages.length) {
        return this.pages[pageIndex];
      }
      return {
        type: 'text',
        content: `This is page ${pageNum} of our ${'nba'.toUpperCase()} book. The content for this page is dynamically generated.`,
        answerKeyUrl: `https://example.com/page-${pageNum}-answers`
      };
    },
    getAnswerKeyUrl(pageNum: number): string {
      const pageConfiguration = this.getPageConfiguration(pageNum);
      return pageConfiguration.answerKeyUrl || `https://example.com/page-${pageNum}-answers`;
    },
    pageExists(pageNum: number): boolean {
      return pageNum >= 1 && pageNum <= this.pages.length;
    }
  }
};

// Aliasing for backward compatibility if ever needed directly (points to nfl by default)
export const pageConfig = booksConfig['nfl'];
